apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rou1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-rou1@sha256:3e58d5aad870b2a31c862dcb8f7adb8533e9e099ec4920632895ce7c2a7860c7
        name: my-nodejs
        resources: {}
status: {}
